### PR TITLE
Add a warning on installation.md before proceeding

### PR DESCRIPTION
**Pull request by babyharpsea**
Well, some people don't seem to have basic Linux knowledge, at least on the support Server. So just making this PR to add a warning that you must have basic Linux knowledge before continuing.

### CODE REVIEW

**Comment by Dviih** [comment]
You made a great thing but this will be "Ignore me"

**Comment by babyharpsea** [comment]
What do you mean?

**Comment by tovade** [comment]
people will just skip the comment and go through with the documentation, it's not worth it tbh

**Comment by babyharpsea** [comment]
Well, they'll just not be given support at all as they were warned, an easy solution after all. Just like how it's made on the Pterodactyl Support server.

**Pull request merged**
